@startuml
left to right direction
title Estrutura de Pacotes do MS de trilha no Sistema de Trilha de Aprendizagem

' Organização de pacotes
package br {
    package edu {
        package ifg {
              package trilhadeaprendizagemapims.trilha {
                    package controller {
                        class TrilhaController
                    }

                    package dto {
                        class TrilhaDTO
                        class ModuloDTO
                        class CategoriaDTO
                    }

                    package model {
                        class Trilha
                        class Modulo
                        class Categoria
                    }

                    package repository {
                        interface TrilhaRepository
                        interface ModuloRepository
                        interface CategoriaRepository
                    }

                    package service {
                        class TrilhaModuloService
                        class CategoriaService
                    }
              }
        }
    }
}

' Dependências entre camadas


@enduml